sms:
  version: 2014-06-30
  restServer: api.ucpaas.com
  validTemplateId: 155770
  agentPwdTemplateId: 191314
  officePwdTemplateId: 191311
  officeResetPwdTemplateId: 234268
  agentResetPwdTemplateId: 234268
  appId: 796e3d30cc074f86a97cd402b7c35398
  accountSid: 08c32a4d179fd602e73617272dcd1a2b
  authToken: 1a0adafcc7b6bffc3e1e52e45aca34a3
  RestUrl: https://api.ucpaas.com
push:
  end20:
    host: http://sdk.open.api.igexin.com/apiex.htm
    appId: k7JWnRjSw7AHDMgsmBbqWA
    appKey: 0Wg7TeuZgK81kmRwF36MD2
    appSecret: rfD14cT6837Eq3tgMSi648
    masterSecret: nPAFy6CQAv6aWz0CKx1yo9
  end30:
    host: http://sdk.open.api.igexin.com/apiex.htm
    appId: B4BE7YUeZd5QK8hHvaBHg9
    appKey: trTY6RzcK37Xs3do47xfQ5
    appSecret: KhY6Pmd7Y49L5FbvQdQu77
    masterSecret: ffX30Uojf8AUwGypQm5nJA